# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8134564e1b10668a9aead3ef329871f4e858ca194452d5965934d54c64dac7e0be716ef9eeb205c6da3f5c4252861f1345252a3ff84533cf5322e139271dd1

test:
  secret_key_base: bb53fb8f2c0a83eb6ebca0084b8b02f6e4804d2f32e10d84c9eaacd32292aa6ec16e28ec9a726d97b0abd6f738b6d6580dc976db4f68ba8b237800e7faecce4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
